name: flutter_application_barber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.1
  dots_indicator: ^3.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  lottie: ^3.1.3
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
